### ISSUE TITLE
How to launch gpsd_client

### ISSUE THREAD

**Issue by felixdivo** [swri-robotics/gps_umd#51]
This one is hopefully easy to solve: How can one launch `gpsd_client`? We are on `foxy` @ Ubuntu 20.04. What I did:

- Install `gps_umd` and `gpsd_client` via `rosdep`
- `ros2 run gpsd_client gpsd_client` -> `No executable found`
- `ros2 launch our.launch.yaml` (see below) -> long stack trace and eventually: `launch.substitutions.substitution_failure.SubstitutionFailure: package 'gpsd_client' found at '/opt/ros/foxy', but libexec directory '/opt/ros/foxy/lib/gpsd_client' does not exist`

Am I missing something abvious? The readme does not mention the node name so maybe that's just what is wrong.

The file `our.launch.yaml` is very short:

```
launch:
  - node:
      pkg: gpsd_client
      exec: gpsd_client
      name: gpsd_client_node
```
